### ISSUE TITLE
fails to serve `dat` web interface

### ISSUE THREAD

**Issue by ajschumacher** [mafintosh/try-dat#6]
Hi! When doing the try-dat adventure-time either on try-dat.com directly or at http://maxogden.github.io/get-dat/ running `dat listen` does not actually make the dat web interface available as promised. All you get is a JSON description of the toy file system. I think this is because https://github.com/mafintosh/docker-adventure-time "uses expose-fs to expose its file system over http" so there's a conflict. Better to not run the dat interface on port 80, maybe? @maxogden

**Comment by karissa** [comment]
This refers to the old dat and we are going to update try-dat for rc1. stay tuned
